"自動インデントで何も入力しないとインデントがなくなるのを何とかする
"Quickfixを使えるようにする
"よく意味の覚えていないオプションを正確に理解する
"visualモードでの:normalのショートカットを探す、または作る
"cindentに切り替えるモード、cppindentなるものも見つけた。
"タブ移動をdじゃなくてuに変える
"NERDTreeのEnterとかの動作を変える

set nocompatible
set cpo&vim
filetype plugin indent on
filetype plugin on

	"------------"
	"    Look    "
	"------------"
syntax enable
set enc=utf-8
set number
set cursorline
set showmatch			" Show matching brackets.
set laststatus=2
set cmdheight=2
set nottybuiltin		" termの探索順序を 外部->組み込み にする
colorscheme railscasts-yuuto	"内部でtermの設定もしている

"Display Tab 
autocmd FileType ruby set list
set listchars=tab:__
highlight SpecialKey ctermfg=161 ctermbg=234  

	"----------"
	"  Action  "
	"----------"
set timeout
set ttimeout			" なくても同じ
set timeoutlen=2500
set ttimeoutlen=100		" よくわかんないけどこれでESCの色適用が遅いのが解決した

set mouse=a
set hidden				" When I have not saved file, can open new file
set clipboard=unnamedplus	"この形なら動作した
set backspace=start,eol,indent
set whichwrap=b,s,[,],<,>,~
"set virtualedit=onemore


	"-------------"
	"Input support"
	"-------------"
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent

"Complete
set completeopt=menu	" Show (partial) command in status line.
set showcmd

"ここらへんの意味がわからない
set matchtime=1

set incsearch		"リアルタイム検索みたいなもの
set hlsearch		"検索候補をハイライト	:noh でハイライトを消す

set wildmenu wildmode=list:full		"cmodeでの補完




	"=============="
	"   Dark vim   "
	"=============="
"#Neobundle
source ~/.vim/neobundle.vim

"#run easy
source ~/.vim/easy-run.vim

"#When insert mode, change status line's color
source ~/.vim/imode-color.vim

"#Keymap
source ~/.vim/keymap.vim



"######################
"######################
	"------------"
	"    Keep    "
	"------------"
"set term=gnome-256color
"set term=xterm-256color	"execute in the railscasts-yuuto

"set term=screen-256color	"あってもなくても動作は変わらなかった
"set term=screen-256color-bce
	"set <xHome>=OH
	"set <xEnd>=OF

"set listchars=tab:\ \	"としたら空白になった

	"-------------"
	"    Trash    "
	"-------------"

