#!/usr/bin/sh

remote_name="${1:?remote name}"
remote_url="${1:?remote url}"
branch_name="$(git rev-parse --abbrev-ref HEAD)"

g remote add "${remote_name}" "${remote_url}"
g fetch "${remote_name}"
g branch --set-remote_name-to="${remote_name}/${branch_name}"
