#!/usr/bin/env zsh

local c
for c in {000..015}; do
  echo -n "\e[38;5;${c}m $c"
  [ $((($c+1)%8)) -eq 0 ] && echo
done

for c in {016..255}; do
  echo -n "\e[38;5;${c}m $c"
  [ $(($((c-16))%6)) -eq 5 ] && echo
done
echo
