#!/usr/bin/zsh

local -a ignore_dirs ignores

ignore_dirs=(.git __pycache__ node_modules '.git-wt-*' .nuxt .next dist cache .bundle)
for dirname in ${ignore_dirs}; do
  ignores+=(-type d -name "${dirname}" -prune -o)
done

find ${ignores} -type d 2>/dev/null | sort -n | peco | head -1
