#!/usr/bin/zsh
# deps to sym_solve relative

save_pwd="${PWD}"
selected='.' # first directory

until [[ -f $selected || -z $selected ]]; do
  cd "${selected}" >/dev/null
  selected="$({ls -AF1 | sym_solve | sort -n; echo '.\n..'} | peco)"
  selected="${selected:a}"
done

cd "${save_pwd}" >/dev/null
selected="$(relative "${selected}")"
echo "${selected}"
