#!/usr/bin/zsh

local -a ignore_dirs ignores
local dirname file

# ripgrepで作り直したほうが良いかも(rustでtargetを除外する必要があって面倒)
#   ignoreする版としない版
# rg --files --color=never --hidden --glob '!.git'
# rg --files --color=never --hidden --glob '!.git' --no-ignore-vcs

ignore_dirs=(.git __pycache__ node_modules '.git-wt-*' .nuxt .next dist cache .bundle)
for dirname in ${ignore_dirs}; do
  ignores+=(-type d -name "${dirname}" -prune -o)
done

target_dir="$(relative "${1:-.}")"

list_dirs_files "${target_dir}" ${ignores} | sort -n | peco | while read file; do
  echo "$(relative "${target_dir}/${file}")"
done
