#!/usr/bin/zsh

dir="$(relative "${1:-.}")"

list_dirs_files "${dir}" -type d -name .git -prune -o -type d -name .bundle -prune -o | sort -n | peco | while read file; do
  echo "$(relative "${dir}/${file}")"
done
