#!/usr/bin/env zsh

git rev-parse --git-dir >&! /dev/null || return

COLOR_RED="#ff6090"
COLOR_GREEN="#23FF48"
COLOR_BLUE="#05E1EB"
COLOR_YELLOW="#FFCF26"
COLOR_MAGENTA="#A75AE8"

# branch name
# branch_name="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
branch_name="$(git branch --show-current 2>/dev/null)"
state_base="$(git status --short --branch 2>/dev/null)"

state="$(echo "${state_base}" | tail --lines=+2 | grep -o '^..')"

if [[ $state =~ U ]]; then
  color="${COLOR_MAGENTA}"
elif [[ $state =~ '\?' ]]; then
  color="${COLOR_YELLOW}"
elif [[ -z $state ]]; then
  color="${COLOR_GREEN}"
elif [[ -z "$(echo $state | grep -o '[^ ]$')" ]]; then
  color="${COLOR_BLUE}"
else
  color="${COLOR_RED}"
fi

# # branch status
brace=$(echo "${state_base}" | head -1 | grep -oe '\[.*]$')
ahead=$(echo "${brace}" | grep -oe 'ahead [0-9]\+' | awk '{print $2}')
behind=$(echo "${brace}" | grep -oe 'behind [0-9]\+' | awk '{print $2}')
# stash=$(git stash list 2>/dev/null | wc -l | sed -e 's/^0$//g')
[[ -n $ahead ]] && ahead=" %F{${COLOR_GREEN}}${ahead}%f"
[[ -n $behind ]] && behind=" %F{${COLOR_RED}}${behind}%f"
[[ -n $stash ]] && stash=" %F{${COLOR_YELLOW}}$stash%f"

echo "[%F{${color}}${branch_name}%f${ahead}${behind}${stash}] "
