#!/usr/bin/env zsh

unset http_proxy
unset HTTP_PROXY
unset https_proxy
unset HTTPS_PROXY
unset ftp_proxy
unset FTP_PROXY
unset rsync_proxy
unset RSYNC_PROXY
unset all_proxy
unset ALL_PROXY
unset no_proxy
unset NO_PROXY
