#!/usr/bin/env zsh

export http_proxy="${1:? server:port}"
export HTTP_PROXY="${http_proxy}"

export https_proxy="${http_proxy}"
export HTTPS_PROXY="${https_proxy}"

export ftp_proxy="${http_proxy}"
export FTP_PROXY="${ftp_proxy}"

export rsync_proxy="${http_proxy}"
export RSYNC_PROXY="${rsync_proxy}"

export all_proxy="${http_proxy}"
export ALL_PROXY="${all_proxy}"

export no_proxy='localhost,127.0.0.1,localaddress,.localdomain.com'
export NO_PROXY="${no_proxy}"
