#!/usr/bin/env zsh

if (($# == 0)); then
  irb --simple-prompt
  return
fi

noglob ruby -r prime -r base64 -r securerandom -r json -r yaml \
  -e "include Math, Base64
      puts eval(ARGV.join(' '))" -- "${*}"
