#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  echo "bisect-grep TEXT [IGNORE_FILE_PATTERNS...]"
  exit 255
fi

text="${1}"
shift

if [[ $# -eq 0 ]]; then
  git grep "${text}"
else
  exclude_patterns=$(export IFS='|'; echo "${*}")
  git grep "${text}" | grep -Ev "^(${exclude_patterns})"
fi
