#!/usr/bin/env ruby

if ARGV.empty?
  puts 'usage: block "start_pattern" ["end_pattern"]'
  puts 'e.g. objdump -S <bin> | block "start_pattern" "end_pattern"'
  exit 1
end

start_pattern = Regexp.new(ARGV.fetch(0).gsub('\n', "\n"))
end_pattern   = Regexp.new(ARGV.fetch(1, '^$').gsub('\n', "\n"))

output_enable = false
while line = STDIN.gets
  if output_enable
    output_enable = false if end_pattern.match?(line)
  elsif start_pattern.match?(line)
    output_enable = true
  end

  puts line if output_enable
end
