#!/usr/bin/env zsh

linux-thermal(){
  # cat /sys/class/thermal/thermal_zone*/temp
  find /sys/class/thermal/ -name 'thermal_zone*' | while read filepath; do
    {
      echo "$(basename "${filepath}")"
      cat  "${filepath}/temp" "${filepath}/type"
    } | tr '\n' ' '
    echo
  done | sort -n -r -k2
}

mac-thermal() {
  sudo powermetrics --samplers smc --sample-count 1
}

case "${OSTYPE:-}" in
  linux*)  linux-thermal ;;
  darwin*) mac-thermal ;;
esac
