#!/usr/bin/env zsh

local arg="${1:-}"
if in_path xclip; then
  if [[ $arg = '-o' ]]; then
    xclip -out -selection clipboard
  elif [[ -z $arg ]]; then
    xclip -in -selection clipboard
  else
    # xclip treat "" as filename.
    xclip -in -selection clipboard "${*}"
  fi
elif in_path xsel; then
  if [[ $arg = '-o' ]]; then
    xsel --clipboard --output
  elif [[ -z $arg ]]; then
    xsel --clipboard --input
  else
    echo "${*}" | xsel --clipboard --input
  fi
elif in_path pbcopy; then
  if [[ $arg = '-o' ]]; then
    pbpaste
  elif [[ -z $arg ]]; then
    pbcopy
  else
    echo "${*}" | pbcopy
  fi
else
  echo "clip: This platform not installed clipboard command(xclip/xsel)." 1>&2
  return 1
fi
