#!/usr/bin/env zsh

if in_darwin; then
  # do nothing
  return
fi

if [[ ${1:-} = '--sound' ]]; then
  sound-alert
  shift
fi

title="${1:?title}"
body="${2:-}"
notify-send --urgency=low --icon="${HOME}/.face.icon" --app-name="${title}" "${title}" "${body}"
