#!/usr/bin/env zsh

if in_darwin; then
  # do nothing
  return
fi

if [[ ${1:-} = '--sound' ]]; then
  play /usr/share/sounds/Oxygen-Sys-Log-In-Short.ogg >&! /dev/null <&- &!
  shift
fi

title="${1:?title}"
body="${2:-}"
notify-send --urgency=low --icon="${HOME}/.face.icon" --app-name="${title}" "${title}" "${body}"
