#!/usr/bin/env ruby

finish_time = ARGV.shift || '^$'

loop do
  # Timeとして比較したほうが良い
  time = Time.now.strftime('%T.%2L')
  print("\r\e[0J#{time}")
  # \e[H\e[2J

  if /#{finish_time}/ =~ time
    system('xdotool mousedown 1')
    sleep(0.03)
    system('xdotool mouseup 1')
    print("\r\e[0J#{Time.now.strftime('%T.%3L')}")
    break
  end

  sleep(0.01)
rescue Interrupt
  exit
end

system('notify "time is now!"')
