#!/usr/bin/env ruby
# frozen_string_literal: true

require 'cgi'

method_name = ('-d' == ARGV.fetch(0, '')) ? :unescape : :escape

while s = $stdin.gets
  puts CGI.send(method_name, s)
end

# if File.pipe?(STDIN)
#   puts url_encode(STDIN.readlines.join)
# elsif not ARGV.empty?
#   puts url_encode(ARGV.join(' '))
# end
