#!/bin/zsh
alias l='ls -F'
alias la='ls -A'
alias ll='ls -l'
alias li='ls -i'
alias lla='ls -lA'
alias lli='ls -li'
alias here='ls -ld $PWD'

function ccd { cd ../${1:-} }
alias cdb="cd -"
alias pu='pushd'
alias po='popd'

# Find
alias findr="find / -name"
alias findh="find ~/ -name"
alias findc="find . -name"

# Vim
alias vi='vim'
alias vizsh="vim ~/.zshrc"
alias vialias="vim ~/.zsh_aliases"
alias vi.simp='\vim -u NONE -N'
alias vi.sjis='vi -c ":e ++enc=cp932"'
alias gv='gvim'
alias nv='nvim'

# Git
alias dotgit='git -C ~/.dotfiles sh'
alias vigit='git -C ~/.vim sh'
alias gs='git s'
alias gst='git st'
alias gd='git d'
alias gdw='git dw'
alias gl='git l'
alias glo='git lo'
alias gsh='git sh'

# utilities
alias envlang="env | egrep --color=never 'LANG|LC'"
alias apt-search='\apt-cache search --names-only'
alias apt-upgrade='apt update && echo "##Upgrade start" && apt upgrade'
alias dirsize='du -csh'
alias resh='exec $SHELL -l'
alias histories="history -E 1"
alias sysv-rc-conf-on='sysv-rc-conf --list | grep :on | sed "s/.:off/     /g"'
alias installed='dpkg --get-selections | grep -v "deinstall" | sed -e "s/[[:space:]]*install$//"'
alias vimopt='vim --version | \egrep "^\+|^-"'

# Clang
alias clang="clang $C_COMP_OPT"
alias clang++="clang++ $CPP_COMP_OPT"

alias gcc="\gcc $GCC_OPT"
alias gccg="\gcc -g $GCC_OPT"
alias gcc32="\gcc -m32 $GCC_OPT"
alias gccg32="\gcc -g -m32 $GCC_OPT"
alias gdb='gdb -q'
alias gdba='gdb -q a.out'
alias objdump='objdump -M intel'

alias irb='irb --simple-prompt'
alias pry='pry --simple-prompt'

# to safely used.
alias mv='mv -iv'
alias cp='cp -iv'
alias rm='rm -v'

# not require sudo
alias shutdown='sudo shutdown'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias apt-get='sudo apt-get'
alias apt='sudo apt'
alias mount='sudo mount'
alias visudo='sudo visudo'

# Suffix
alias -s py='python'
alias -s rb='ruby'
alias -s php='php -f'
alias -s {gif,jpg,jpeg,png,bmp}='display'
alias -s {html,htm}='opera-beta'
alias -s c='runc'
alias -s cpp='runcpp'
function runcpp { clang++ $1 -o ${1%.*} && ./${1%.*} }
function runc { clang $1 -o ${1%.*} && ./${1%.*} }

# Global
alias -g G='2>&1 | grep'
alias -g L='2>&1 | less'
alias -g H='2>&1 | head'
alias -g M='2>&1 | more'
alias -g T='2>&1 | tail'
alias -g C='2>&1 | cat'
alias -g X='2>&1 | xargs'
alias -g W='2>&1 | wc'
alias -g A='2>&1 | awk'
alias -g S='2>&1 | sed'
alias -g N='> /dev/null'
alias -g E='2> /dev/null'
alias -g Q='> /dev/null 2>&1'
alias -g B='> /dev/null 2>&1 &'

# Directory aliases
hash -d vim=$HOME/.vim/
hash -d zsh=$HOME/.dotfiles/zsh/
hash -d dotfiles=$HOME/.dotfiles/
hash -d code=$HOME/code/
hash -d ruby=$HOME/code/ruby/
hash -d rails=$HOME/code/rails/
hash -d utilities=$HOME/code/utilities/

# New and other aliases
alias twme='tw `tw -user:default`'
alias be='bundle exec'
