#!/bin/zsh
exists_source $HOME/code/ruby/memo/memo_completion.zsh

#cdの補完関数を利用して保管する
_ch(){
  CDPATH=$HOME
  _cd "cd"
}
compdef _ch ch

_cr(){
  CDPATH="/"
  _cd "cd"
}
compdef _cr cr

  # _values `echo '@'; ls -F $HOME/.vim/`
  # _files -P "$HOME/.vim/"
_viconf(){
  PREFIX=$HOME/.vim/
	local ctl
	if {
			zstyle -s ":completion:${curcontext}:" use-compctl ctl || zmodload -e zsh/compctl
		} && [[ "$ctl" != (no|false|0|off) ]]
	then
		local opt
		opt=()
		[[ "$ctl" = *first* ]] && opt=(-T)
		[[ "$ctl" = *default* ]] && opt=("$opt[@]" -D)
		compcall "$opt[@]" || return 0
	fi
	_files "$@" && return 0
	if [[ -o magicequalsubst && "$PREFIX" = *\=* ]]
	then
		compstate[parameter]="${PREFIX%%\=*}"
		compset -P 1 '*='
		_value "$@"
	else
		return 1
	fi
  popd
}
compdef _viconf viconf
zstyle ':completion:*:viconf' list-colors ${(s.:.)LS_COLORS}
