#!/usr/bin/env zsh
#login interactive scriptの全てから参照される

#unique属性を付加
typeset -U path PATH MANPATH INFOPATH fpath

in_path(){
  which $@ &>! /dev/null
}

can_exec(){
  type $@ &>! /dev/null
}

exists_source(){
  [[ ! -f "$1" ]] && return 0
  source "${1}"
}

export LANGUAGE=en
export LANG=en_US.UTF-8 # Provides default value for LC_* variables.

export WORDCHARS='*?!#%[]{}<>()~`\' # ^$&@_+-:;|.
export EDITOR=vim
export VISUAL=vim

export PAGER='less -i' #最低限共通部分
export MANPAGER='less -i --RAW-CONTROL-CHARS --LONG-PROMPT --chop-long-lines'

export GZIP='-v9N'
export WWW_BROWSER=w3m
export DOWNLOADER="wget -S"
# export TERM=screen-256color-bce # italicが使えない
[[ -z "$TMUX" ]] && export TERM='xterm-256color'

if [[ -z $TMUX ]]; then
  export TERM='xterm-256color'

  if [[ -n "${REMOTEHOST:-}${SSH_CONNECTION:-}" ]]; then
    in_path tmux && exec tmux
  fi
fi

export C_CPP_WALL_OPT='-Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-ignored-qualifiers'
export C_COMP_OPT="$C_CPP_WALL_OPT -lm -std=c11"
export CPP_COMP_OPT="$C_CPP_WALL_OPT -std=c++1z"
export GCC_OPT="$C_COMP_OPT -O0 -fno-stack-protector"
export REPO_HTTPS='https://github.com/YuutoIto'
export REPO_SSH='git@github.com:YuutoIto'
export ZSH_DOT_DIR="$(dirname "$(readlink -f $HOME/.zshenv)")"
export DOT_DIR="$(dirname "${ZSH_DOT_DIR}")"

# Order is important
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

if [[ -d $HOME/.rbenv/bin ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  in_path rbenv && eval "$(rbenv init - zsh)"
elif in_path gem; then
  export PATH="${$(gem environment gempath)%%:*}/bin:$PATH"
fi

export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

if [[ -n "${WINDOWID:-}" && -f $HOME/.xmodmap ]]; then
  xmodmap ~/.xmodmap
fi

stty -ixon -ixoff
