#!/usr/bin/env zsh
#login interactive scriptの全てから参照される

#unique属性を付加
typeset -U path PATH MANPATH INFOPATH

export EDITOR=vim
# italicが使えない
# export TERM=screen-256color-bce
export WORDCHARS='*?:;[]{}<>|~\!#%`@+-'
export C_CPP_WALL_OPT='-Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-ignored-qualifiers'
export C_COMP_OPT="$C_CPP_WALL_OPT -lm -std=c11"
export CPP_COMP_OPT="$C_CPP_WALL_OPT -std=c++1z"
export GCC_OPT="$C_COMP_OPT -O0 -fno-stack-protector"
export REPO_HTTPS='https://github.com/YuutoIto'
export REPO_SSH='git@github.com:YuutoIto'
export YLIBS="$HOME/code/ylibs"
export YLIB_CPP="$YLIBS/cpp"
export YLIB_RUBY="$YLIBS/ruby"

# Order is important
export PATH="$HOME/.rbenv/bin:$PATH"
which rbenv > /dev/null
[[ $? -eq 0 ]] && eval "$(rbenv init -)"
export PATH="./bundle_bin:$HOME/bin:$HOME/.local/bin:$PATH"

function exists_source(){
  if [[ -f "$1" ]]; then
    source $1
  else
    return 1
  fi
}

if [ -n "${WINDOWID-}" -a -f $HOME/.xmodmap ]; then
	xmodmap ~/.xmodmap
fi

stty -ixon -ixoff #これがないと何故かvimでC-Sが使えない
