#!/usr/bin/env zsh
# zmodload zsh/zprof && zprof

## For ssh and tty
[[ ! -z "${ZSHENV_LOADED:-}" ]] && return
ZSHENV_LOADED="loaded"

## add unique attr
typeset -U path PATH MANPATH INFOPATH fpath FPATH MANPATH NODE_PATH # RUBYLIB

in_path(){
  which $@ &>! /dev/null
}

can_exec(){
  type $@ &>! /dev/null
}

exists_source(){
  [[ ! -f "$1" ]] && return 0
  source "${1}"
}

in_ssh(){
  [[ -n "${REMOTEHOST:-}${SSH_CONNECTION:-}" ]]
}

in_tmux(){
  [[ -n "${TMUX:-}" ]]
}

export PATH="${HOME}/.local/bin:${PATH}:/usr/local/bin:${DOT_DIR}/git-subcommands"

## Directories
export ZSH_DOT_DIR="$(dirname "$(readlink $HOME/.zshenv)")"
export DOT_DIR="$(dirname "${ZSH_DOT_DIR}")"
export MOUNT='/run/media/uplus'

case "${OSTYPE:-}" in
  linux*)  source "$ZSH_DOT_DIR/zshrc.linux" ;;
  darwin*) source "$ZSH_DOT_DIR/zshrc.darwin" ;;
esac

export skip_global_compinit=1

# export LANGUAGE=en # don't need?
export LANG=en_US.UTF-8 # Provides default value for LC_* variables.

export WORDCHARS='*?!#%[]{}<>()~`\' # ^$&@_+-:;|.

## Editer config
if in_path nvim; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export GIT_EDITOR="${EDITOR}"
export VISUAL="${EDITOR}"

## Pager config
export PAGER='less --ignore-case --RAW-CONTROL-CHARS --LONG-PROMPT'
export MANPAGER="${PAGER} --chop-long-lines"
export GIT_PAGER="${PAGER} --chop-long-lines --quit-if-one-screen --no-init"


export WWW_BROWSER=w3m
export DOWNLOADER='wget -S'
# export TERM=screen-256color-bce # italicが使えない
in_tmux || export TERM='xterm-256color'

export C_CPP_WALL_OPT='-Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-ignored-qualifiers'
export C_COMP_OPT="$C_CPP_WALL_OPT -lm -std=c11"
export CPP_COMP_OPT="$C_CPP_WALL_OPT -std=c++1z"
export GCC_OPT="$C_COMP_OPT -O0 -fno-stack-protector"
# export DOCKER_CONTENT_TRUST=1
export NMAP_PRIVILEGED="" # set privilege mode to nmap
export RUSTFLAGS='-A dead_code -A unused_imports -A  unused_variables -A unused_macros'
# export RUBYOPT='-w'


# export LC_ALL=en_US.UTF-8 # LC_COLLATE is not working, evil /etc/profile
# export LC_COLLATE=C

if [[ -d $HOME/.rbenv/bin ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  in_path rbenv && eval "$(rbenv init - zsh)"
elif in_path gem; then
  export PATH="${$(gem environment gempath)%%:*}/bin:$PATH"
fi

export RUBYLIB="$HOME/.rubylib/:${RUBYLIB}"
export GOPATH="$HOME/.go"
export NPM_PACKAGES="$HOME/.npm-packages"

export PATH="$GOPATH/bin:$PATH"
export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/.cabal/bin:${PATH}"
export PATH="${NPM_PACKAGES}/bin:${PATH}"
export NODE_PATH="${NPM_PACKAGES}/lib/node_modules:${NODE_PATH}"

# export MANPATH="${NPM_PACKAGES}/share/man:$(manpath)"

if [[ -z $USER ]]; then
  export USER="$(whoami)"
fi

# if [[ -n "${WINDOWID:-}" && -f $HOME/.xmodmap ]]; then
#   xmodmap ~/.xmodmap
# fi

[[ $- == *i* ]] && stty -ixon -ixoff >&! /dev/null

export PATH="${HOME}/bin:${PATH}"

# /etc/zsh/profile -> /etc/profileで爆発しないようプロテクト
# readonly PATH

# for recover PATH
PATH_keep="${PATH}"
